#!/usr/bin/env python3
"""Import real ``.map`` sources into ``corpus/``.

The differential harness (§3.3) is only as good as its corpus, and synthetic maps cannot
tell you whether you handle what real tools actually emit. Three sources, in descending
order of value:

``corpus/real/``
    The user's own Urban Terror map sources. Highest value: real brush-primitives maps,
    real patches, real long decimals, written by the actual editor.

``corpus/regression/``
    ``vendor/netradiant-custom/regression_tests/q3map2/``. Deliberately pathological maps
    kept by upstream — ``degenerate_winding``, ``duplicate_plane``, ``disappearing_sliver``,
    ``tiny_structural_brush``, ``snap_plane``. This is a far better degenerate-case suite
    than anything we would think to invent, and it comes with upstream's own opinion about
    what the compiler should do with each.

``corpus/synthetic/``
    Generated by ``tools/gen_corpus.py``, covering format combinations the other two miss
    (notably Valve 220, which appears in neither).

Everything imported is made **read-only**. Sources outside the repo are copied, never
referenced in place and never written to: ``corpus/real`` originates inside a Windows
``Program Files`` install of someone's game, and a tool that corrupts a mapper's own
levels while testing that it does not corrupt maps would be difficult to explain.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import stat
import sys
from dataclasses import dataclass, asdict
from pathlib import Path

# Editor leavings that duplicate a real source without adding format coverage.
SKIP_SUFFIXES = (".autosave.map", ".bak")


@dataclass
class Imported:
    name: str
    bytes: int
    source: str
    origin: str


def repo_root() -> Path:
    return Path(os.environ.get("NRC_ROOT") or Path(__file__).resolve().parent.parent)


def make_read_only(p: Path) -> None:
    """Drop write bits. Best-effort: a DrvFs mount may not honour chmod."""
    try:
        p.chmod(p.stat().st_mode & ~(stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH))
    except OSError:
        pass


def copy_in(src: Path, dest_dir: Path, source_label: str, out: list[Imported]) -> None:
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / src.name
    # Overwriting a read-only destination needs the write bit back first.
    if dest.exists():
        try:
            dest.chmod(dest.stat().st_mode | stat.S_IWUSR)
        except OSError:
            pass
    shutil.copyfile(src, dest)
    make_read_only(dest)
    out.append(
        Imported(
            name=src.name,
            bytes=dest.stat().st_size,
            source=source_label,
            origin=str(src),
        )
    )


def import_game_maps(root: Path, out: list[Imported]) -> list[str]:
    notes: list[str] = []
    raw = os.environ.get("URT_MAPSRC")
    if not raw:
        notes.append("URT_MAPSRC is unset — skipping game map sources (set it in mise.local.toml)")
        return notes
    src_dir = Path(raw)
    if not src_dir.is_dir():
        notes.append(f"URT_MAPSRC={src_dir} is not a directory — skipping")
        return notes

    found = sorted(src_dir.glob("*.map"))
    for m in found:
        if any(m.name.endswith(s) for s in SKIP_SUFFIXES):
            continue
        copy_in(m, root / "corpus" / "real", "game-install", out)
    notes.append(f"scanned {src_dir} ({len(found)} .map files present)")
    return notes


def import_regression_maps(root: Path, out: list[Imported]) -> list[str]:
    notes: list[str] = []
    base = Path(os.environ.get("NRC_SRC") or (root / "vendor" / "netradiant-custom"))
    reg = base / "regression_tests"
    if not reg.is_dir():
        notes.append(f"{reg} not present — run `mise run vendor:clone` first")
        return notes

    dest = root / "corpus" / "regression"
    count = 0
    for m in sorted(reg.rglob("*.map")):
        # Case directories are the interesting label; flatten but keep it in the name so a
        # failure report says *which* pathology broke.
        case = m.relative_to(reg).parts
        label = case[1] if len(case) > 2 else m.stem
        target = dest / f"{label}__{m.name}" if label != m.stem else dest / m.name
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            try:
                target.chmod(target.stat().st_mode | stat.S_IWUSR)
            except OSError:
                pass
        shutil.copyfile(m, target)
        make_read_only(target)
        out.append(
            Imported(
                name=target.name,
                bytes=target.stat().st_size,
                source="upstream-regression",
                origin=str(m),
            )
        )
        count += 1
    notes.append(f"imported {count} upstream regression maps from {reg}")
    return notes


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--manifest",
        default="corpus/MANIFEST.json",
        help="where to record provenance (relative to the repo root)",
    )
    args = ap.parse_args()

    root = repo_root()
    imported: list[Imported] = []
    notes: list[str] = []
    notes += import_game_maps(root, imported)
    notes += import_regression_maps(root, imported)

    manifest_path = root / args.manifest
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(
            {
                "note": "Generated by tools/import_corpus.py. Imported maps are read-only "
                "copies; the originals are never modified.",
                "counts": {
                    src: sum(1 for i in imported if i.source == src)
                    for src in sorted({i.source for i in imported})
                },
                "maps": [asdict(i) for i in imported],
            },
            indent=2,
        )
        + "\n"
    )

    for n in notes:
        print(f"  {n}")
    by_source: dict[str, int] = {}
    for i in imported:
        by_source[i.source] = by_source.get(i.source, 0) + 1
    if not imported:
        print("no maps imported — the corpus will fall back to synthetic maps only")
        return 0
    total_kb = sum(i.bytes for i in imported) / 1024
    print(f"imported {len(imported)} maps ({total_kb:.0f} KiB): {by_source}")
    print(f"manifest: {manifest_path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
