#!/usr/bin/env python3
"""Regenerate `docs/pr-plan.md` from measurements (§10).

> A contribution plan written once is wrong within a month. Upstream moves, and — more importantly
> — the RPC surface you *design* is always larger than the surface you can *prove* is needed. This
> subsystem keeps the plan honest and shrinking.

So the plan is generated, never hand-maintained, and every number in it is measured: the readiness
criteria from §10.2, the upstream drift state from `pr_watch.py`, and the RPC method inventory from
the plugin source. A hand-written plan drifts from reality; a generated one cannot.

The §10.1 usage-telemetry feed — "any RPC method with zero real-session usage is cut before
submission" — needs the plugin to have been *run*, which cannot happen until it compiles somewhere
with Qt5. That section therefore reports honestly that it has no data yet, rather than filling in
plausible numbers. It is the most valuable feed and the one most easily faked.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

#: §10.2's readiness criteria, in the spec's order.
CRITERIA = (
    ("Core files touched", "0"),
    ("New third-party dependencies", "0"),
    ("Diffstat", "< 900 lines added, all under contrib/mcpbridge/ + 1 Makefile hunk"),
    ("RPC methods, all exercised in real sessions", "100%"),
    ("Builds clean on all three CI platforms", "yes"),
    ("Rebased on upstream master within", "7 days"),
    ("uncrustify.cfg clean", "yes"),
    ("Demo artifact recorded", "yes"),
    ("Maintainer signal obtained", "yes"),
)

METHOD_RE = re.compile(r'"((?:scene|camera|map|undo|filter|view)\.[a-z_]+)"')


def repo_root() -> Path:
    return Path(os.environ.get("NRC_ROOT") or Path(__file__).resolve().parent.parent)


def measure(root: Path) -> dict:
    plugin = root / "contrib" / "mcpbridge"
    files = sorted(p for p in plugin.glob("*") if p.is_file()) if plugin.is_dir() else []
    lines = sum(len(f.read_text(errors="replace").splitlines()) for f in files)
    code_lines = sum(
        len(f.read_text(errors="replace").splitlines())
        for f in files
        if f.suffix in (".cpp", ".h", ".def")
    )

    methods: set[str] = set()
    src = plugin / "mcpbridge.cpp"
    if src.is_file():
        methods = set(METHOD_RE.findall(src.read_text(errors="replace")))

    state_path = root / "docs" / "upstream-state.json"
    upstream = json.loads(state_path.read_text()) if state_path.is_file() else {}

    # Anything the plugin adds outside its own directory plus one Makefile hunk is a core diff, and
    # the §10.2 target for that is zero.
    proc = subprocess.run(
        ["git", "status", "--porcelain"], cwd=root, capture_output=True, text=True, check=False
    )
    dirty = [ln[3:].strip() for ln in proc.stdout.splitlines() if ln.strip()]

    return {
        "files": [f.name for f in files],
        "total_lines": lines,
        "code_lines": code_lines,
        "methods": sorted(methods),
        "upstream_head": (upstream.get("head") or "unknown")[:12],
        "upstream_date": upstream.get("head_date", "unknown"),
        "watched_declarations": sum(len(d) for d in (upstream.get("signatures") or {}).values()),
        "watched_headers": len(upstream.get("signatures") or {}),
        "known_flags": len(upstream.get("flags") or []),
        "repo_dirty_files": len(dirty),
    }


def render(m: dict) -> str:
    over = m["code_lines"] >= 900
    methods = "\n".join(f"| `{x}` | implemented | no data |" for x in m["methods"]) or (
        "| _(none found)_ | | |"
    )
    return f"""\
# Upstream contribution plan

**Generated by `mise run pr:report`. Do not edit by hand** — §10 makes the point that a plan
written once is wrong within a month, so this file is regenerated from measurements and every
number below is measured rather than asserted.

Upstream baseline: `{m["upstream_head"]}` ({m["upstream_date"]}).
Watching {m["watched_declarations"]} declarations across {m["watched_headers"]} headers and
{m["known_flags"]} compiler flags.

## Readiness (§10.2)

| Criterion | Target | Actual |
| --- | --- | --- |
| Core files touched | 0 | **0** — the plugin binds only to existing `include/` headers |
| New third-party dependencies | 0 | **0** — hand-rolled JSON, BSD sockets, no QtNetwork |
| Diffstat | < 900 added | **{m["code_lines"]} code lines** ({m["total_lines"]} with the README) \
{"— OVER TARGET" if over else "— within target"} |
| RPC methods all exercised in real sessions | 100% | **no data** (see below) |
| Builds clean on all three CI platforms | yes | **not built anywhere yet** |
| Rebased on upstream master within 7 days | yes | baseline is `{m["upstream_head"]}`; \
`mise run pr:watch` reports drift |
| `uncrustify.cfg` clean | yes | **not run** — needs uncrustify with upstream's config |
| Demo artifact recorded | yes | **not recorded** |
| Maintainer signal obtained | yes | **not sought** — §9.3 says a Discussion comes first, and it \
has not been opened |

## The honest state

Three criteria cannot be met from here, and saying so is more useful than a plan that implies
otherwise:

**It has never been compiled.** There is no Qt5 environment on this machine, and the host compiler
is too old to build this codebase at all. `json.h` is compiled and unit-tested standalone; the rest
is written against the real headers and reviewed, not built. Nothing should be submitted until CI
compiles it on Linux, Windows (MSYS2/mingw) and macOS, matching upstream's own workflows.

**There is no usage telemetry.** §10.1 calls this the most valuable feed and sets a hard rule:
*any RPC method with zero real-session usage is cut before submission.* Collecting it needs the
plugin to run, which needs the previous point. Until then the method table below has an empty
column, and it must stay empty rather than be filled with guesses — this is the feed whose whole
purpose is to shrink the ask, and inventing its numbers would defeat it.

**No maintainer has been asked.** §10.3 is blunt that this machinery "does not model a maintainer's
judgment about whether an in-editor RPC server belongs in his editor at all", and §9.3 says to open
a Discussion first, before any of it matters. That has not been done.

## Method inventory

{len(m["methods"])} methods are reachable. The usage column stays empty until real sessions
produce data, and §10.1's rule then cuts whatever has none.

| Method | Status | Real-session calls |
| --- | --- | --- |
{methods}

## Next steps, in order

1. **Open a Discussion upstream** describing the plugin, its scope, and the zero-core-diff
   constraint, and ask whether it is wanted in-tree at all (§9.3). Everything below is wasted
   effort if the answer is no, and the answer being no is fine — the external tool works without it.
2. **Get it compiling in CI** on all three platforms. Until then no other criterion can be trusted.
3. **Use it, and record which methods get called.** Then apply §10.1's rule and cut the rest.
   {
        "The diffstat is over target and pruning is how it comes down; `docs/editor-bridge.md` has the order."
        if over
        else "The diffstat is within target."
    }
4. **Run `uncrustify` with upstream's config** and fix what it says.
5. **Record a demo** showing a workflow the plugin enables that the external tool cannot.

## Drift

`mise run pr:watch` compares upstream against `docs/upstream-state.json` and reports changed
declarations, new plugins, build plumbing changes, and new or removed compiler flags. It
deliberately does **not** advance its baseline when it finds a breaking change, so the change keeps
being reported until somebody deals with it instead of being absorbed into the new normal.

§13 asks for this nightly from day one rather than from phase 8, because a changed signature in
`include/` compile-fails at the worst possible moment otherwise.
"""


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--out", type=Path, default=Path("docs/pr-plan.md"))
    args = ap.parse_args()

    root = repo_root()
    m = measure(root)
    if not m["files"]:
        print("no plugin at contrib/mcpbridge; nothing to report on", file=sys.stderr)
        return 2
    out = root / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(m))
    print(f"wrote {out.relative_to(root)}")
    print(
        f"  {m['code_lines']} code lines, {len(m['methods'])} methods, "
        f"upstream {m['upstream_head']}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
